// Generated by CoffeeScript 1.7.1
(function() {
  var PROGRAM, VERSION, cli, fs, help, main, nopt, path, pkg, _;

  fs = require("fs");

  path = require("path");

  _ = require("underscore");

  nopt = require("nopt");

  pkg = require("../package.json");

  main = require("./main");

  PROGRAM = pkg.name;

  VERSION = pkg.version;

  cli = exports;

  exports.main = function() {
    var args, cmdOptions, envOptions, ignored, optionName, optionRec, options, parsed, shortOptions, _ref;
    options = {
      port: ["p", Number],
      verbose: ["v", Boolean],
      help: ["h", Boolean]
    };
    shortOptions = {
      "?": ["--help"]
    };
    for (optionName in options) {
      optionRec = options[optionName];
      if (optionRec[0] !== "") {
        shortOptions[optionRec[0]] = ["--" + optionName];
      }
    }
    for (optionName in options) {
      optionRec = options[optionName];
      options[optionName] = optionRec[1];
    }
    parsed = nopt(options, shortOptions, process.argv, 2);
    args = parsed.argv.remain;
    if ((_ref = args[0]) === "?" || _ref === "help") {
      return help();
    }
    if (parsed.help) {
      return help();
    }
    cmdOptions = {};
    for (optionName in options) {
      ignored = options[optionName];
      if (parsed[optionName] != null) {
        cmdOptions[optionName] = parsed[optionName];
      }
    }
    envOptions = {};
    envOptions.port = process.env.PORT;
    options = _.defaults(cmdOptions, envOptions);
    return main.start(options);
  };

  help = function() {
    console.log("" + PROGRAM + " " + VERSION + "\n\n    runs a " + PROGRAM + " server\n\nusage: " + PROGRAM + " [options]\n\noptions:\n    -p --port NUMBER     tcp/ip to run server on\n    -v --verbose         be verbose\n    -h --help            print this help\n\nThe port can also be specified by setting the PORT environment variable.");
  };

  if (require.main === module) {
    exports.run();
  }

}).call(this);
