// Generated by CoffeeScript 1.7.1
(function() {
  var Q, Server, main, pkg, stop;

  Q = require("q");

  pkg = require("../package.json");

  Server = require("./server");

  main = exports;

  main.version = pkg.version;

  main.start = function(options) {
    var deferred, server;
    server = new Server(options);
    deferred = Q.defer();
    server.start(function(error) {
      var serverShell;
      if (error) {
        return deferred.reject(error);
      }
      serverShell = {
        port: server.port,
        stop: function() {
          return stop(server);
        }
      };
      return deferred.resolve(serverShell);
    });
    return deferred.promise;
  };

  stop = function(server) {
    var deferred;
    deferred = Q.defer();
    server.stop(function(error) {
      if (error) {
        return deferred.reject(error);
      }
      return deferred.resolve(null);
    });
    return deferred.promise;
  };

}).call(this);
